### ISSUE TITLE
Does not work properly with the Hermes JS engine

### ISSUE THREAD

**Issue by andreialecu** [Kjens93/react-native-font-faces#289]
I've been scratching my head for a while on this and went on to troubleshoot it.

It appears that on Android when using Hermes, this library is not able to pick the correct font via the `matchFontFace` function.

The reason this seems to occur is because Hermes does not have a stable sort function: https://github.com/facebook/hermes/issues/212 so this piece of code does not work properly: https://github.com/kylerjensen/react-native-font-faces/blob/5cde7092564ac76fa9d0ac512a53b7077273ab05/src/utilities/matchFontFace.ts#L13-L20

Any subsequent sort will then randomize the sort order.

I think a fix could be to add a dependency on a third party library to do the sorting instead of using the built in sort function.

What do you think?

**Comment by kylerjensen** [comment]
@andreialecu This looks good to me, thanks for the PR!
